<?php
include('file/header.php');
include('file/_banner-area.php');
include('file/_banner_adds.php');
include('file/_special-price.php');
include('file/_top-sale.php');
include('file/_new-phones.php');
include('file/_blogs.php');
include('file/footer.php');
